Add files via upload

diff --git a/Story/storyt b/Story/storyt
--- a/Story/storyt
+++ b/Story/storyt
@@ -1,4 +1,6 @@
 #!/bin/bash
+MAGNETA=$(tput setaf 5)
+RESET=$(tput sgr0)
 
 while true
 do
@@ -12,10 +14,17 @@ curl -s https://raw.githubusercontent.com/111STAVR111/props/main/logo_1.txt | ba
 PS3='Select an action: '
 options=(
 "Install Node"
+"Check Story logs"
+"Check Geth logs"
+"Sync status"
+"Check sync info"
+"Check validator info"
 "Create wallet"
-"Check node logs"
-"Synchronization via StateSync"
-"Synchronization via SnapShot"
+"Check wallet info"
+"Check wallet balance"
+"Check Version"
+"Synchronization via SnapShot (Pruned)"
+"Synchronization via SnapShot (Archive)"
 "UPDATE"
 "Delete Node"
 "Exit")
@@ -35,13 +44,37 @@ echo export Validator_Name=${Validator_Name} >> $HOME/.bash_profile
 echo export CHAIN_ID="iliad" >> $HOME/.bash_profile
 source ~/.bash_profile
 
+# Спросить о смене портов сразу после ввода имени валидатора
+echo -e "\e[1m\e[32m	DO YOU WANT TO CHANGE THE DEFAULT PORTS? (y/n):\e[0m"
+read change_ports
+
+if [ "$change_ports" == "y" ]; then
+    # Сохраним новые префиксы для портов
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the proxy_app port (26658):\e[0m"
+    read proxy_app_prefix
+
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the rpc port (26657):\e[0m"
+    read rpc_prefix
+
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the p2p port (26656):\e[0m"
+    read p2p_prefix
+
+    # Проверьте ввод
+    if ! [[ "$proxy_app_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$rpc_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$p2p_prefix" =~ ^[0-9]{2}$ ]]; then
+        echo "Invalid input. Ports will not be changed."
+        change_ports="n"  # Игнорировать изменения, если ввод не в правильном формате
+    fi
+fi
+
 echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
-#UPDATE APT
+# UPDATE APT
 sudo apt update && sudo apt upgrade -y
 sudo apt install curl tar wget clang pkg-config libssl-dev libleveldb-dev jq build-essential bsdmainutils git make ncdu htop screen unzip bc fail2ban htop -y
+echo "${MAGNETA}🔥Dependencies updated 🔥${RESET}"
+sleep 1
 
 echo -e "        \e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
-#INSTALL GO
+# INSTALL GO
 ver="1.21.6"
 wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
 sudo rm -rf /usr/local/go
@@ -50,9 +83,11 @@ rm "go$ver.linux-amd64.tar.gz"
 echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $HOME/.bash_profile
 source $HOME/.bash_profile
 go version
+echo "${MAGNETA}🔥GO is installed 🔥${RESET}"
+sleep 1
 
 echo -e "              \e[1m\e[32m3. Downloading and building binaries--> \e[0m" && sleep 1
-#INSTALL
+# INSTALL
 cd $HOME && mkdir -p go/bin/
 wget https://story-geth-binaries.s3.us-west-1.amazonaws.com/geth-public/geth-linux-amd64-0.9.3-b224fdf.tar.gz
 tar -xvf geth-linux-amd64-0.9.3-b224fdf.tar.gz
@@ -65,12 +100,25 @@ go build -o story ./client
 sudo mv $HOME/story/story $HOME/go/bin/
 mkdir -p ~/.story/story
 mkdir -p ~/.story/geth
-
+echo "${MAGNETA}🔥Binaries installed successfully 🔥${RESET}"
+sleep 1
+# Инициализируем узел
 story init --network $CHAIN_ID --moniker $Validator_Name
 
+# Изменяем порты после инициализации
+if [ "$change_ports" == "y" ]; then
+    sed -i "s/tcp:\/\/127\.0\.0\.1:26658/tcp:\/\/127.0.0.1:${proxy_app_prefix}658/" $HOME/.story/story/config/config.toml
+    sed -i "s/tcp:\/\/127\.0\.0\.1:26657/tcp:\/\/127.0.0.1:${rpc_prefix}657/" $HOME/.story/story/config/config.toml
+    sed -i "s/tcp:\/\/0\.0\.0\.0:26656/tcp:\/\/0.0.0.0:${p2p_prefix}656/" $HOME/.story/story/config/config.toml
+    echo "Ports have been updated to ${proxy_app_prefix}658, ${rpc_prefix}657, and ${p2p_prefix}656."
+fi
+
 wget -O $HOME/.story/story/config/addrbook.json "https://raw.githubusercontent.com/111STAVR111/props/main/Story/addrbook.json"
-
-
+PEERS="27e144520559066334215c661a999e35ca8a3c40@160.25.233.228:26656,8876a2351818d73c73d97dcf53333e6b7a58c114@3.225.157.207:26656,8c1b516805e0c4631306032a0108e51339ab7cfd@78.46.60.145:26656,065107237cbe9aef0644cf1312902e157ecac71c@14.180.187.186:11156,f1e8a864dd243b89e58b4722af0d46bc3f9782a0@65.108.40.171:26656,f16c644a6d19798e482edcfe5bd5728a22aa5e0d@65.108.103.184:26656,4fe74768c4dabc66b3b75bace62e0446307cac7e@story-testnet.rpc.kjnodes.com:26656,aac5871efa351872789eef15c2da7a55a68abdad@88.218.226.79:26656,d0adad9344de86d8cde2ba65d07dbab0680d56dd@story-testnet-cosmos-rpc.crouton.digital:29856,800bd9a3bb37a07d5c57c42a5de72d7ab370cfd1@157.173.121.44:26656,bf023f368a0db72cae3931ff33a9a1b6c78db3fb@65.108.107.50:25656,c80927677db61cba41154a1341b133c1b7442ed4@49.12.120.113:25356,c82d2b5fe79e3159768a77f25eee4f22e3841f56@3.209.222.59:26656,1cceccb08bae25a0f91fe85b0ca562fa791f47aa@184.169.154.204:26656,1e8c2d47630cbeb16b3311888aac643598a00ace@65.108.129.170:24056,15c7e2b630c04ee11b2c3cfbfb1ede0379df9407@52.74.117.64:26656,359e4420e63db005d8e39c490ad1c1c329a68df3@3.222.216.118:26656,07ab4164e1d0ee17c565542856ac58981537156f@37.27.124.51:42656,0b512c9a4421c0259813aaa05c865f82365fa7c0@3.1.137.11:26656,5d7507dbb0e04150f800297eaba39c5161c034fe@135.125.188.77:26656"
+sed -i -e "/^\[p2p\]/,/^\[/{s/^[[:space:]]*persistent_peers *=.*/persistent_peers = \"$PEERS\"/}" $HOME/.story/story/config/config.toml
+echo "${MAGNETA}🔥Ports and peers updated 🔥${RESET}"
+sleep 1
+# Setup systemd services
 sudo tee /etc/systemd/system/story-geth.service > /dev/null <<EOF
 [Unit]
 Description=Story Geth Client
@@ -104,19 +152,19 @@ LimitNOFILE=4096
 WantedBy=multi-user.target
 EOF
 
-
-# start service
+# Start and enable services
 sudo systemctl daemon-reload
 sudo systemctl enable story-geth
 sudo systemctl enable story
 sudo systemctl restart story-geth
 sudo systemctl restart story
+echo "${MAGNETA}🔥Service files are installed and running 🔥${RESET}"
 
 echo '=============== SETUP FINISHED ==================='
 echo -e 'Congratulations:        \e[1m\e[32mSUCCESSFUL NODE INSTALLATION\e[0m'
 echo -e 'To check logs:        \e[1m\e[33mjournalctl -fu story-geth -o cat\e[0m'
 echo -e 'To check logs:        \e[1m\e[33mjournalctl -fu story -o cat\e[0m'
-echo -e "To check sync status: \e[1m\e[35mcurl -s http://localhost:26657/status | jq .result.sync_info\e[0m"
+echo -e "To check sync status: \e[1m\e[35mcurl -s http://localhost:${rpc_prefix}657/status | jq .result.sync_info\e[0m"
 
 break
 ;;
@@ -132,13 +180,26 @@ echo -e "      \e[1m\e[32m!!!!!!!!!SAVE!!!!!!!!!!!!!!!!SAVE YOUR PRICATE KEY!!!!
 
 break
 ;;
-"Synchronization via StateSync")
-echo -e "      \e[1m\e[32m SOOOON\e[0m"
+"Synchronization via SnapShot (Archive)")
+cd $HOME
+snap install lz4
+sudo systemctl stop story
+sudo systemctl stop story-geth
+cp $HOME/.story/story/data/priv_validator_state.json $HOME/.story/story/priv_validator_state.json.backup
+rm -rf $HOME/.story/story/data
+rm -rf $HOME/.story/geth/iliad/geth/chaindata
+curl -o - -L https://story-archive.snapshot.stavr.tech/story-snap.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.story/story/
+curl -o - -L https://story-archive.snapshot.stavr.tech/story_geth-snap.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.story/geth/iliad/geth/
+mv $HOME/.story/story/priv_validator_state.json.backup $HOME/.story/story/data/priv_validator_state.json
+wget -O $HOME/.story/story/config/addrbook.json "https://raw.githubusercontent.com/111STAVR111/props/main/Story/addrbook.json"
+sudo systemctl restart story-geth
+sudo systemctl restart story && sudo journalctl -fu story -ocat
 
 
 break
 ;;
 "UPDATE")
+echo -e "      \e[1m\e[32m SOOOON\e[0m"
 cd $HOME
 rm -rf story
 git clone https://github.com/piplabs/story
@@ -146,16 +207,21 @@ cd $HOME/story
 git checkout v0.10.1
 go build -o story ./client
 sudo mv $HOME/story/story $(which story)
-sudo systemctl restart story && sudo journalctl -fu story -ocat
+sudo systemctl restart story && journalctl -fu story -ocat
 
 break
 ;;
-"Check node logs")
-sudo journalctl -fu story-geth.service -o cat
+"Check Story logs")
+sudo journalctl -fu story -ocat
 
 break
 ;;
-"Synchronization via SnapShot")
+"Check Geth logs")
+sudo journalctl -fu story-geth -ocat
+
+break
+;;
+"Synchronization via SnapShot (Pruned)")
 cd $HOME
 snap install lz4
 sudo systemctl stop story story-geth
@@ -172,18 +238,97 @@ sudo systemctl restart story && sudo journalctl -fu story -ocat
 
 break
 ;;
+"Check validator info")
+curl localhost:$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $HOME/.story/story/config/config.toml)/status | jq
+
+break
+;;
+"Check wallet info")
+story validator export
+
+break
+;;
+"Check Version")
+story_output=$(story version 2>&1)
+echo -e "\e[32m${story_output}\e[0m"
+
+# Для geth version вывод также должен быть в жёлтом цвете, построчно
+geth version 2>&1 | head -n 4 | while IFS= read -r line; do
+    echo -e "\e[33m${line}\e[0m"
+done
+
+
+break
+;;
+"Check wallet balance")
+echo "_|-_|-_|-_|-_|-_|-_|"
+echo -e "      \e[1m\e[35m Enter your EVM Address:\e[0m"
+echo "_|-_|-_|-_|-_|-_|-_|"
+read EVMADDRESS
+
+BALANCE=$(geth --exec "eth.getBalance('$EVMADDRESS')" attach ~/.story/geth/iliad/geth.ipc 2>/dev/null)
+BALANCE_ETH=$(awk "BEGIN {printf \"%.18f\", $BALANCE/1000000000000000000}")
+
+echo "Balance: $BALANCE_ETH IP"
+
+break
+;;
+"Check sync info")
+RPC_PORT=$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $HOME/.story/story/config/config.toml)
+curl -s http://localhost:$RPC_PORT/status | jq .result.sync_info
+
+break
+;;
+"Sync status")
+# Извлекаем номер порта из config.toml
+RPC_PORT=$(sed -n '90{s/.*://; s/"//g; p}' /root/.story/story/config/config.toml)
+
+while true; do
+    local_height=$(curl -s localhost:$RPC_PORT/status | jq -r '.result.sync_info.latest_block_height')
+    network_height=$(curl -s https://story.rpc-archive.t.stavr.tech/status | jq -r '.result.sync_info.latest_block_height')
+    blocks_left=$((network_height - local_height))
+    
+    # Расчётное время до полной синхронизации в секундах
+    estimated_time=$(echo "$blocks_left * 2.80" | bc)
+    
+    # Перевод в часы и минуты
+    hours=$(echo "$estimated_time / 3600" | bc)
+    minutes=$(echo "($estimated_time % 3600) / 60" | bc)
+
+    # Вывод со стилем
+    echo -e "\033[1;38mYour height:\033[0m \033[1;32m$local_height\033[0m | \033[1;35mNetwork height:\033[0m \033[1;36m$network_height\033[0m | \033[1;29mBlocks left:\033[0m \033[1;31m$blocks_left\033[0m | \033[1;33mEstimated time: $hours hours $minutes minutes\033[0m"
+    sleep 5
+done
+
+
+
+break
+;;
 "Delete Node")
-sudo systemctl stop story-geth
-sudo systemctl disable story-geth
-sudo systemctl stop story
-sudo systemctl disable story
-rm /etc/systemd/system/story-geth.service
-rm /etc/systemd/system/story.service
-sudo systemctl daemon-reload
-cd $HOME
-rm -rf .story
-rm -rf $(which story)
-rm -rf $(which geth)
+echo -e "\e[31mAre you sure you want to delete the node? (Yes/No):\e[0m"
+read confirmation
+
+if [ "$confirmation" == "Yes" ]; then
+    echo -e "\e[32m$confirmation\e[0m - Starting deletion process."
+
+    sudo systemctl stop story-geth
+    sudo systemctl disable story-geth
+    sudo systemctl stop story
+    sudo systemctl disable story
+    sudo rm /etc/systemd/system/story-geth.service
+    sudo rm /etc/systemd/system/story.service
+    sudo systemctl daemon-reload
+    cd $HOME
+    rm -rf .story
+    rm -rf story
+    rm -rf geth-linux-amd64-0.9.3-b224fdf
+    rm -rf $(which story)
+    rm -rf $(which geth)
+
+    echo "Node has been successfully deleted."
+else
+    echo "Node deletion cancelled."
+fi
 
 break
 ;;
