Update teritorm

diff --git a/Teritori/teritorm b/Teritori/teritorm
--- a/Teritori/teritorm
+++ b/Teritori/teritorm
@@ -1,4 +1,6 @@
 #!/bin/bash
+MAGNETA=$(tput setaf 5)
+RESET=$(tput sgr0)
 
 while true
 do
@@ -12,10 +14,14 @@ curl -s https://raw.githubusercontent.com/111STAVR111/props/main/logo_1.txt | ba
 PS3='Select an action: '
 options=(
 "Install Node"
+"Check logs"
+"Sync status"
+"Check sync info"
+"Check validator info"
 "Create wallet"
-"Check node logs"
-"Synchronization via StateSync"
-"Synchronization via SnapShot"
+"Check Version"
+"Synchronization via Statesync"
+"Synchronization via SnapShot (Pruned)"
 "UPDATE"
 "Delete Node"
 "Exit")
@@ -34,14 +40,37 @@ echo "_|-_|-_|-_|-_|-_|-_|"
 echo export Validator_Name=${Validator_Name} >> $HOME/.bash_profile
 echo export CHAIN_ID="teritori-1" >> $HOME/.bash_profile
 source ~/.bash_profile
+echo -e "\e[1m\e[32m	DO YOU WANT TO CHANGE THE DEFAULT PORTS? (yes/no):\e[0m"
+read change_ports
+change_ports=$(echo "$change_ports" | tr '[:upper:]' '[:lower:]')
+if [[ "$change_ports" == "yes" || "$change_ports" == "y" ]]; then
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the proxy_app port (26658):\e[0m"
+    read proxy_app_prefix
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the rpc port (26657):\e[0m"
+    read rpc_prefix
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the p2p port (26656):\e[0m"
+    read p2p_prefix
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the pprof port (6060):\e[0m"
+    read pprof_prefix
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the grpc port (9090):\e[0m"
+    read grpc_prefix
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the grpc-web port (9091):\e[0m"
+    read grpc_web_prefix
+    if ! [[ "$proxy_app_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$rpc_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$p2p_prefix" =~ ^[0-9]{2}$ ]]; then
+        echo "Invalid input. Ports will not be changed."
+        change_ports="n"
+    fi
+fi
 
 echo -e "\e[1m\e[32m1. Updating packages and dependencies--> \e[0m" && sleep 1
-#UPDATE APT
+# UPDATE APT
 sudo apt update && sudo apt upgrade -y
 sudo apt install curl tar wget clang pkg-config libssl-dev libleveldb-dev jq build-essential bsdmainutils git make ncdu htop screen unzip bc fail2ban htop -y
+echo "${MAGNETA}🔥Dependencies updated 🔥${RESET}"
+sleep 1
 
 echo -e "        \e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
-#INSTALL GO
+# INSTALL GO
 ver="1.21.6"
 wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
 sudo rm -rf /usr/local/go
@@ -50,23 +79,39 @@ rm "go$ver.linux-amd64.tar.gz"
 echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $HOME/.bash_profile
 source $HOME/.bash_profile
 go version
+echo "${MAGNETA}🔥GO is installed 🔥${RESET}"
+sleep 1
 
 echo -e "              \e[1m\e[32m3. Downloading and building binaries--> \e[0m" && sleep 1
-#INSTALL
+# INSTALL
 cd $HOME && mkdir -p go/bin/
 git clone https://github.com/TERITORI/teritori-chain
 cd teritori-chain 
 git checkout v2.0.6
 make install
-
+echo "${MAGNETA}🔥Binaries installed successfully 🔥${RESET}"
+sleep 1
 teritorid init $Validator_Name --chain-id $CHAIN_ID
 
-cd $HOME
-wget -O ~/.teritorid/config/genesis.json https://media.githubusercontent.com/media/TERITORI/teritori-chain/v1.1.2/mainnet/teritori-1/genesis.json
-wget -O $HOME/.teritorid/config/addrbook.json "https://raw.githubusercontent.com/111STAVR111/props/main/Teritori/addrbook.json"
+if [ "$change_ports" == "y" ]; then
+    echo "Changing proxy_app port..."
+    sed -i "s/tcp:\/\/127\.0\.0\.1:26658/tcp:\/\/127.0.0.1:${proxy_app_prefix}658/" $HOME/.teritorid/config/config.toml
+    echo "Changing rpc port..."
+    sed -i "s/tcp:\/\/127\.0\.0\.1:26657/tcp:\/\/127.0.0.1:${rpc_prefix}657/" $HOME/.teritorid/config/config.toml
+    echo "Changing p2p port..."
+    sed -i "s/tcp:\/\/0\.0\.0\.0:26656/tcp:\/\/0.0.0.0:${p2p_prefix}656/" $HOME/.teritorid/config/config.toml
+    echo "Changing pprof port..."
+    sed -i "s/pprof_laddr = \"localhost:6060\"/pprof_laddr = \"localhost:${pprof_prefix}60\"/" $HOME/.teritorid/config/config.toml
+    echo "Changing grpc port..."
+    sed -i "s/address = \"localhost:9090\"/address = \"localhost:${grpc_prefix}90\"/" $HOME/.teritorid/config/app.toml
+    echo "Changing grpc-web port..."
+    sed -i "s/address = \"localhost:9091\"/address = \"localhost:${grpc_web_prefix}91\"/" $HOME/.teritorid/config/app.toml
+    echo "Ports have been updated to ${proxy_app_prefix}658, ${rpc_prefix}657, ${p2p_prefix}656, ${pprof_prefix}60, ${grpc_prefix}90 and ${grpc_web_prefix}91."
+fi
 
-echo -e "                     \e[1m\e[32m4. Node optimization and improvement--> \e[0m" && sleep 1
 
+wget -O $HOME/.teritorid/config/addrbook.json "https://server-1.stavr.tech/Mainnet/Teritori/addrbook.json"
+wget -L -O $HOME/.teritorid/config/genesis.json https://server-1.stavr.tech/Mainnet/Teritori/genesis.json
 sed -i.bak -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.0utori\"/;" ~/.teritorid/config/app.toml
 sed -i -e "s/^filter_peers *=.*/filter_peers = \"true\"/" $HOME/.teritorid/config/config.toml
 external_address=$(wget -qO- eth0.me) 
@@ -78,7 +123,6 @@ sed -i.bak -e "s/^seeds =.*/seeds = \"$seeds\"/" $HOME/.teritorid/config/config.
 sed -i 's/max_num_inbound_peers =.*/max_num_inbound_peers = 50/g' $HOME/.teritorid/config/config.toml
 sed -i 's/max_num_outbound_peers =.*/max_num_outbound_peers = 10/g' $HOME/.teritorid/config/config.toml
 
-# pruning
 pruning="custom"
 pruning_keep_recent="1000"
 pruning_keep_every="0"
@@ -87,31 +131,35 @@ sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.teritorid/config/app.
 sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.teritorid/config/app.toml
 sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.teritorid/config/app.toml
 sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.teritorid/config/app.toml
-
-
+echo "${MAGNETA}🔥Ports and peers updated 🔥${RESET}"
+sleep 1
+# Setup systemd services
 sudo tee /etc/systemd/system/teritorid.service > /dev/null <<EOF
 [Unit]
 Description=Teritorid
 After=network-online.target
+
 [Service]
 User=$USER
 ExecStart=$(which teritorid) start
 Restart=on-failure
 RestartSec=3
 LimitNOFILE=65535
+
 [Install]
 WantedBy=multi-user.target
 EOF
 
-# start service
+# Start and enable services
 sudo systemctl daemon-reload
 sudo systemctl enable teritorid
 sudo systemctl restart teritorid
+echo "${MAGNETA}🔥Service files are installed and running 🔥${RESET}"
 
 echo '=============== SETUP FINISHED ==================='
 echo -e 'Congratulations:        \e[1m\e[32mSUCCESSFUL NODE INSTALLATION\e[0m'
-echo -e 'To check logs:        \e[1m\e[33mjournalctl -u teritorid -f -o cat\e[0m'
-echo -e "To check sync status: \e[1m\e[35mcurl -s localhost:26657/status\e[0m"
+echo -e 'To check logs:        \e[1m\e[33mjournalctl -fu teritorid -o cat\e[0m'
+echo -e "To check sync status: \e[1m\e[35mcurl -s http://localhost:${rpc_prefix}657/status | jq .result.sync_info\e[0m"
 
 break
 ;;
@@ -127,12 +175,22 @@ echo -e "      \e[1m\e[32m!!!!!!!!!SAVE!!!!!!!!!!!!!!!!SAVE YOUR MNEMONIC PHRASE
 
 break
 ;;
-"Synchronization via StateSync")
+"UPDATE")
+echo -e "      \e[1m\e[32m SOOOON\e[0m"
+teritorid version
+
+break
+;;
+"Check logs")
+sudo journalctl -fu teritorid -ocat
+
+break
+;;
+"Synchronization via Statesync")
+systemctl stop teritorid
 SNAP_RPC=https://teritori.rpc.m.stavr.tech:443
-peers="ab77fecd8c58d89a1bd28bc198449aa2d7fb8740@teritori.peers.stavr.tech:38026"
-sed -i.bak -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/.teritorid/config/config.toml
 LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height); \
-BLOCK_HEIGHT=$((LATEST_HEIGHT - 300)); \
+BLOCK_HEIGHT=$((LATEST_HEIGHT - 1000)); \
 TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)
 
 echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH
@@ -142,41 +200,173 @@ s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ; \
 s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ; \
 s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"| ; \
 s|^(seeds[[:space:]]+=[[:space:]]+).*$|\1\"\"|" $HOME/.teritorid/config/config.toml
-teritorid tendermint unsafe-reset-all --home $HOME/.teritorid
-curl -o - -L https://teritori.wasm.stavr.tech/wasm-teritori.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.teritorid --strip-components 2
-wget -O $HOME/.teritorid/config/addrbook.json "https://raw.githubusercontent.com/111STAVR111/props/main/Teritori/addrbook.json"
+teritorid tendermint unsafe-reset-all --home /root/.teritorid
+wget -O $HOME/.teritorid/config/addrbook.json "https://server-1.stavr.tech/Mainnet/Teritori/addrbook.json"
+curl -o - -L https://teritori.wasm.stavr.tech/wasm-teritori.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.teritorid
 sudo systemctl restart teritorid && journalctl -fu teritorid -o cat
 
-break
-;;
-"UPDATE")
-cd $HOME/teritori-chain/
-git pull
-git checkout v2.0.6
-make install
-sudo systemctl restart teritorid && journalctl -u teritorid -f -o cat
 
 break
 ;;
-"Check node logs")
-sudo journalctl -u teritorid -f -o cat
-
-break
-;;
-"Synchronization via SnapShot")
+"Synchronization via SnapShot (Pruned)")
 cd $HOME
-apt install lz4
-sudo systemctl stop teritorid
-cp $HOME/.teritorid/data/priv_validator_state.json $HOME/.teritorid/priv_validator_state.json.backup
-rm -rf $HOME/.teritorid/data
-curl -o - -L https://teritori.snapshot.stavr.tech/teritori-snap.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.teritorid --strip-components 2
-mv $HOME/.teritorid/priv_validator_state.json.backup $HOME/.teritorid/data/priv_validator_state.json
-wget -O $HOME/.teritorid/config/addrbook.json "https://raw.githubusercontent.com/111STAVR111/props/main/Teritori/addrbook.json"
-sudo systemctl restart teritorid && journalctl -fu teritorid -o cat
+YELLOW='\033[1;33m'
+GREEN='\033[1;32m'
+PINK='\033[1;35m'
+BLUE='\033[1;34m'
+NO_COLOR='\033[0m'
+
+SNAPSHOT_INFO_URLS=("https://server-1.stavr.tech/Mainnet/Teritori/snapshot-1-info.txt" 
+                    "https://server-1.stavr.tech/Mainnet/Teritori/snapshot-2-info.txt" 
+                    "https://server-1.stavr.tech/Mainnet/Teritori/snapshot-3-info.txt")
+
+SNAPSHOT_INFO=()
+SNAPSHOT_BLOCK_HEIGHT=()
+SNAPSHOT_CREATION_TIME=()
+SNAPSHOT_FILE_SIZE=()
+
+RED='\033[0;31m'
+YELLOW='\033[1;33m'
+GREEN='\033[1;32m'
+PINK='\033[1;35m'
+NO_COLOR='\033[0m'
+
+declare -a SNAPSHOT_BLOCK_HEIGHT
+declare -a SNAPSHOT_CREATION_TIME
+declare -a SNAPSHOT_FILE_SIZE
+
+for i in "${!SNAPSHOT_INFO_URLS[@]}"; do
+    INFO_URL=${SNAPSHOT_INFO_URLS[i]}
+    
+    if curl --output /dev/null --silent --head --fail "$INFO_URL"; then
+        INFO=$(curl -s "$INFO_URL")
+        BLOCK_HEIGHT=$(echo "$INFO" | grep "Block height" | awk '{print $3}')
+        CREATION_TIME_RAW=$(echo "$INFO" | grep "Creation time" | cut -d ':' -f2- | xargs)
+        CREATION_TIME_FORMATTED=$(date -d "$CREATION_TIME_RAW" +"%Y-%m-%d %H:%M:%S" 2>/dev/null)
+        
+        if [ $? -ne 0 ]; then
+            CREATION_TIME_FORMATTED="Invalid date format"
+        else
+            CREATION_TIME_EPOCH=$(date -d "$CREATION_TIME_RAW" +%s)
+            CURRENT_TIME_EPOCH=$(date +%s)
+            TIME_DIFF=$((CURRENT_TIME_EPOCH - CREATION_TIME_EPOCH))
+
+            if ((TIME_DIFF < 60)); then
+                TIME_AGO="${TIME_DIFF} sec ago"
+            elif ((TIME_DIFF < 3600)); then
+                TIME_AGO="$((TIME_DIFF / 60)) min ago"
+            elif ((TIME_DIFF < 86400)); then
+                TIME_AGO="$((TIME_DIFF / 3600)) h ago"
+            else
+                TIME_AGO="$((TIME_DIFF / 86400)) d ago"
+            fi
+        fi
+        
+        FILE_SIZE=$(echo "$INFO" | grep "Pruned size" | awk '{print $3}')
+        SNAPSHOT_BLOCK_HEIGHT+=("${BLOCK_HEIGHT:-N/A}")
+        SNAPSHOT_CREATION_TIME+=("${CREATION_TIME_FORMATTED:-N/A}")
+        SNAPSHOT_FILE_SIZE+=("${FILE_SIZE:-N/A}")
+        SNAPSHOT_TIME_AGO+=("${TIME_AGO:-N/A}")
+    else
+        SNAPSHOT_BLOCK_HEIGHT+=("N/A")
+        SNAPSHOT_CREATION_TIME+=("N/A")
+        SNAPSHOT_FILE_SIZE+=("N/A")
+        SNAPSHOT_TIME_AGO+=("N/A")
+    fi
+done
+
+for i in "${!SNAPSHOT_BLOCK_HEIGHT[@]}"; do
+    echo -e "${RED}Snapshot $((i + 1))${NO_COLOR}"
+    echo -e "Block Height: ${YELLOW}${SNAPSHOT_BLOCK_HEIGHT[i]}${NO_COLOR}"
+    echo -e "Creation Time: ${GREEN}${SNAPSHOT_CREATION_TIME[i]}${NO_COLOR}"
+    echo -e "Time Ago: ${BLUE}${SNAPSHOT_TIME_AGO[i]}${NO_COLOR}"  # Вывод времени
+    echo -e "File Size (Pruned): ${PINK}${SNAPSHOT_FILE_SIZE[i]}${NO_COLOR}"
+    echo ""
+done
+
+
+AVAILABLE_SNAPSHOTS=0
+for height in "${SNAPSHOT_BLOCK_HEIGHT[@]}"; do
+    if [[ "$height" != "N/A" ]]; then
+        ((AVAILABLE_SNAPSHOTS++))
+    fi
+done
+
+if [[ $AVAILABLE_SNAPSHOTS -gt 0 ]]; then
+    read -p "Please choose a snapshot number (1-${#SNAPSHOT_BLOCK_HEIGHT[@]}): " SNAPSHOT_CHOICE
+    if [[ "$SNAPSHOT_CHOICE" =~ ^[1-9][0-9]*$ ]] && [ "$SNAPSHOT_CHOICE" -le "${#SNAPSHOT_BLOCK_HEIGHT[@]}" ]; then
+        SELECTED_BLOCK_HEIGHT=${SNAPSHOT_BLOCK_HEIGHT[$((SNAPSHOT_CHOICE-1))]}
+        echo "You chose snapshot: Snapshot $SNAPSHOT_CHOICE with Block Height: $SELECTED_BLOCK_HEIGHT"
+        
+        read -p "Do you want to continue with synchronization via the selected snapshot? (yes/no): " USER_CHOICE
+        USER_CHOICE=$(echo "$USER_CHOICE" | tr '[:upper:]' '[:lower:]')
+
+        if [[ "$USER_CHOICE" == "yes" || "$USER_CHOICE" == "y" ]]; then
+            echo "Proceeding with synchronization..."
+            snap list | grep -q lz4 || snap install lz4
+            sudo systemctl stop teritorid
+            cp $HOME/.teritorid/data/priv_validator_state.json $HOME/.teritorid/priv_validator_state.json.backup
+            rm -rf $HOME/.teritorid/data
+            SNAPSHOT_NUMBER=$((SNAPSHOT_CHOICE))
+            curl -o - -L "https://server-1.stavr.tech/Mainnet/Teritori/teritori-snap-$SNAPSHOT_NUMBER.tar.lz4" | lz4 -c -d - | tar -x -C $HOME/.teritorid
+            mv $HOME/.teritorid/priv_validator_state.json.backup $HOME/.teritorid/data/priv_validator_state.json
+            wget -O $HOME/.teritorid/config/addrbook.json "https://server-1.stavr.tech/Mainnet/Teritori/addrbook.json"
+            sudo systemctl restart teritorid && journalctl -fu teritorid -o cat
+        else
+            echo "Operation cancelled. Returning to menu..."
+        fi
+    else
+        echo "Invalid selection. Returning to menu..."
+    fi
+else
+    echo "No available snapshots to select. Returning to menu..."
+fi
+
+
+break
+;;
+"Check validator info")
+curl localhost:$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $HOME/.teritorid/config/config.toml)/status | jq
+
+break
+;;
+"Check Version")
+version_output=$(teritorid version --long | grep -e version -e commit 2>&1)
+echo -e "\e[32m${version_output}\e[0m"
+
+break
+;;
+"Check sync info")
+RPC_PORT=$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $HOME/.teritorid/config/config.toml)
+curl -s http://localhost:$RPC_PORT/status | jq .result.sync_info
+
+break
+;;
+"Sync status")
+RPC_PORT=$(grep '^laddr' $HOME/.teritorid/config/config.toml | head -n 1 | awk -F':' '{print $NF}' | tr -d '"')
+while true; do
+    local_height=$(curl -s localhost:$RPC_PORT/status | jq -r '.result.sync_info.latest_block_height')
+    network_height=$(curl -s https://teritori.rpc.m.stavr.tech/status | jq -r '.result.sync_info.latest_block_height')
+    blocks_left=$((network_height - local_height))
+    
+    estimated_time=$(echo "$blocks_left * 1.60" | bc)
+    
+    hours=$(echo "$estimated_time / 3600" | bc)
+    minutes=$(echo "($estimated_time % 3600) / 60" | bc)
+
+    echo -e "\033[1;38mYour height:\033[0m \033[1;32m$local_height\033[0m | \033[1;35mNetwork height:\033[0m \033[1;36m$network_height\033[0m | \033[1;29mBlocks left:\033[0m \033[1;31m$blocks_left\033[0m | \033[1;33mEstimated time: $hours hours $minutes minutes\033[0m"
+    sleep 5
+done
 
 break
 ;;
 "Delete Node")
+echo -e "\e[31mAre you sure you want to delete the node? (Yes/No):\e[0m"
+read confirmation
+
+if [ "$confirmation" == "Yes" ]; then
+    echo -e "\e[32m$confirmation\e[0m - Starting deletion process."
+
 sudo systemctl stop teritorid
 sudo systemctl disable teritorid
 rm /etc/systemd/system/teritorid.service
@@ -185,6 +375,11 @@ cd $HOME
 rm -rf .teritorid
 rm -rf teritori-chain
 rm -rf $(which teritorid)
+
+    echo "Node has been successfully deleted."
+else
+    echo "Node deletion cancelled."
+fi
 
 break
 ;;
