Update prysmt

diff --git a/Prysm/prysmt b/Prysm/prysmt
--- a/Prysm/prysmt
+++ b/Prysm/prysmt
@@ -54,6 +54,8 @@ if [[ "$change_ports" == "yes" || "$change_ports" == "y" ]]; then
     read pprof_prefix
     echo -e "\e[1m\e[32m	Enter the new first two digits for the grpc port (9090):\e[0m"
     read grpc_prefix
+    echo -e "\e[1m\e[32m	Enter the new first two digits for the grpc-web port (9091):\e[0m"
+    read grpc_web_prefix
     if ! [[ "$proxy_app_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$rpc_prefix" =~ ^[0-9]{2}$ ]] || ! [[ "$p2p_prefix" =~ ^[0-9]{2}$ ]]; then
         echo "Invalid input. Ports will not be changed."
         change_ports="n"
@@ -69,7 +71,7 @@ sleep 1
 
 echo -e "        \e[1m\e[32m2. Installing GO--> \e[0m" && sleep 1
 # INSTALL GO
-ver="1.22.2"
+ver="1.21.6"
 wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
 sudo rm -rf /usr/local/go
 sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
@@ -101,11 +103,14 @@ if [ "$change_ports" == "y" ]; then
     sed -i "s/pprof_laddr = \"localhost:6060\"/pprof_laddr = \"localhost:${pprof_prefix}60\"/" $HOME/.prysm/config/config.toml
     echo "Changing grpc port..."
     sed -i "s/address = \"localhost:9090\"/address = \"localhost:${grpc_prefix}90\"/" $HOME/.prysm/config/app.toml
-    echo "Ports have been updated to ${proxy_app_prefix}658, ${rpc_prefix}657, ${p2p_prefix}656, ${pprof_prefix}60 and ${grpc_prefix}90."
+    echo "Changing grpc-web port..."
+    sed -i "s/address = \"localhost:9091\"/address = \"localhost:${grpc_web_prefix}91\"/" $HOME/.prysm/config/app.toml
+    echo "Ports have been updated to ${proxy_app_prefix}658, ${rpc_prefix}657, ${p2p_prefix}656, ${pprof_prefix}60, ${grpc_prefix}90 and ${grpc_web_prefix}91."
 fi
 
-wget -O $HOME/.prysm/config/addrbook.json "https://raw.githubusercontent.com/111STAVR111/props/refs/heads/main/Prysm/addrbook.json"
-wget -O $HOME/.prysm/config/genesis.json "https://raw.githubusercontent.com/111STAVR111/props/refs/heads/main/Prysm/genesis.json"
+
+wget -O $HOME/.prysm/config/addrbook.json "https://server-1.stavr.tech/Testnet/Prysm/addrbook.json"
+wget -O $HOME/.prysm/config/genesis.json "https://server-1.stavr.tech/Testnet/Prysm/genesis.json"
 sed -i.bak -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.001uprysm\"/;" ~/.prysm/config/app.toml
 external_address=$(wget -qO- eth0.me) 
 sed -i.bak -e "s/^external_address *=.*/external_address = \"$external_address:26656\"/" $HOME/.prysm/config/config.toml
@@ -115,6 +120,15 @@ seeds=""
 sed -i.bak -e "s/^seeds =.*/seeds = \"$seeds\"/" $HOME/.prysm/config/config.toml
 sed -i 's/max_num_inbound_peers =.*/max_num_inbound_peers = 50/g' $HOME/.prysm/config/config.toml
 sed -i 's/max_num_outbound_peers =.*/max_num_outbound_peers = 50/g' $HOME/.prysm/config/config.toml
+
+pruning="custom"
+pruning_keep_recent="1000"
+pruning_keep_every="0"
+pruning_interval="10"
+sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.prysm/config/app.toml
+sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.prysm/config/app.toml
+sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.prysm/config/app.toml
+sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.prysm/config/app.toml
 echo "${MAGNETA}🔥Ports and peers updated 🔥${RESET}"
 sleep 1
 # Setup systemd services
@@ -171,19 +185,23 @@ sudo journalctl -fu prysmd -ocat
 break
 ;;
 "Synchronization via Statesync")
+systemctl stop prysmd
 SNAP_RPC=https://prysm.rpc.t.stavr.tech:443
 LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height); \
 BLOCK_HEIGHT=$((LATEST_HEIGHT - 1000)); \
 TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)
+
+echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH
+
 sed -i.bak -E "s|^(enable[[:space:]]+=[[:space:]]+).*$|\1true| ; \
 s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ; \
 s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ; \
 s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"| ; \
 s|^(seeds[[:space:]]+=[[:space:]]+).*$|\1\"\"|" $HOME/.prysm/config/config.toml
 prysmd tendermint unsafe-reset-all --home /root/.prysm
-wget -O $HOME/.prysm/config/addrbook.json "https://prysm-t.wasm.stavr.tech/addrbook.json"
-curl -o - -L https://prysm-t.wasm.stavr.tech/wasm-prysm.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.prysm/
+wget -O $HOME/.prysm/config/addrbook.json "https://server-1.stavr.tech/Testnet/Prysm/addrbook.json"
 sudo systemctl restart prysmd && journalctl -fu prysmd -o cat
+
 
 break
 ;;
@@ -192,47 +210,113 @@ cd $HOME
 YELLOW='\033[1;33m'
 GREEN='\033[1;32m'
 PINK='\033[1;35m'
+BLUE='\033[1;34m'
 NO_COLOR='\033[0m'
-SNAPSHOT_INFO_URL="https://prysm-t.snapshot.stavr.tech/snapshot-info.txt"
-SNAPSHOT_INFO=$(curl -s $SNAPSHOT_INFO_URL)
 
-BLOCK_HEIGHT=$(echo "$SNAPSHOT_INFO" | grep "Block height" | awk '{print $3}')
-CREATION_TIME_RAW=$(echo "$SNAPSHOT_INFO" | grep "Creation time" | cut -d ' ' -f3-)
+SNAPSHOT_INFO_URLS=("https://server-1.stavr.tech/Testnet/Prysm/snapshot-1-info.txt" 
+                    "https://server-1.stavr.tech/Testnet/Prysm/snapshot-2-info.txt" 
+                    "https://server-1.stavr.tech/Testnet/Prysm/snapshot-3-info.txt")
 
-CREATION_TIME_EPOCH=$(date -d "$CREATION_TIME_RAW" +%s)
-CURRENT_TIME_EPOCH=$(date +%s)
-TIME_DIFF=$((CURRENT_TIME_EPOCH - CREATION_TIME_EPOCH))
+SNAPSHOT_INFO=()
+SNAPSHOT_BLOCK_HEIGHT=()
+SNAPSHOT_CREATION_TIME=()
+SNAPSHOT_FILE_SIZE=()
 
-if ((TIME_DIFF < 60)); then
-    TIME_AGO="${TIME_DIFF} sec ago"
-elif ((TIME_DIFF < 3600)); then
-    TIME_AGO="$((TIME_DIFF / 60)) min ago"
-elif ((TIME_DIFF < 86400)); then
-    TIME_AGO="$((TIME_DIFF / 3600)) h ago"
+RED='\033[0;31m'
+YELLOW='\033[1;33m'
+GREEN='\033[1;32m'
+PINK='\033[1;35m'
+NO_COLOR='\033[0m'
+
+declare -a SNAPSHOT_BLOCK_HEIGHT
+declare -a SNAPSHOT_CREATION_TIME
+declare -a SNAPSHOT_FILE_SIZE
+
+for i in "${!SNAPSHOT_INFO_URLS[@]}"; do
+    INFO_URL=${SNAPSHOT_INFO_URLS[i]}
+    
+    if curl --output /dev/null --silent --head --fail "$INFO_URL"; then
+        INFO=$(curl -s "$INFO_URL")
+        BLOCK_HEIGHT=$(echo "$INFO" | grep "Block height" | awk '{print $3}')
+        CREATION_TIME_RAW=$(echo "$INFO" | grep "Creation time" | cut -d ':' -f2- | xargs)
+        CREATION_TIME_FORMATTED=$(date -d "$CREATION_TIME_RAW" +"%Y-%m-%d %H:%M:%S" 2>/dev/null)
+        
+        if [ $? -ne 0 ]; then
+            CREATION_TIME_FORMATTED="Invalid date format"
+        else
+            CREATION_TIME_EPOCH=$(date -d "$CREATION_TIME_RAW" +%s)
+            CURRENT_TIME_EPOCH=$(date +%s)
+            TIME_DIFF=$((CURRENT_TIME_EPOCH - CREATION_TIME_EPOCH))
+
+            if ((TIME_DIFF < 60)); then
+                TIME_AGO="${TIME_DIFF} sec ago"
+            elif ((TIME_DIFF < 3600)); then
+                TIME_AGO="$((TIME_DIFF / 60)) min ago"
+            elif ((TIME_DIFF < 86400)); then
+                TIME_AGO="$((TIME_DIFF / 3600)) h ago"
+            else
+                TIME_AGO="$((TIME_DIFF / 86400)) d ago"
+            fi
+        fi
+        
+        FILE_SIZE=$(echo "$INFO" | grep "Pruned size" | awk '{print $3}')
+        SNAPSHOT_BLOCK_HEIGHT+=("${BLOCK_HEIGHT:-N/A}")
+        SNAPSHOT_CREATION_TIME+=("${CREATION_TIME_FORMATTED:-N/A}")
+        SNAPSHOT_FILE_SIZE+=("${FILE_SIZE:-N/A}")
+        SNAPSHOT_TIME_AGO+=("${TIME_AGO:-N/A}")
+    else
+        SNAPSHOT_BLOCK_HEIGHT+=("N/A")
+        SNAPSHOT_CREATION_TIME+=("N/A")
+        SNAPSHOT_FILE_SIZE+=("N/A")
+        SNAPSHOT_TIME_AGO+=("N/A")
+    fi
+done
+
+for i in "${!SNAPSHOT_BLOCK_HEIGHT[@]}"; do
+    echo -e "${RED}Snapshot $((i + 1))${NO_COLOR}"
+    echo -e "Block Height: ${YELLOW}${SNAPSHOT_BLOCK_HEIGHT[i]}${NO_COLOR}"
+    echo -e "Creation Time: ${GREEN}${SNAPSHOT_CREATION_TIME[i]}${NO_COLOR}"
+    echo -e "Time Ago: ${BLUE}${SNAPSHOT_TIME_AGO[i]}${NO_COLOR}"  # Вывод времени
+    echo -e "File Size (Pruned): ${PINK}${SNAPSHOT_FILE_SIZE[i]}${NO_COLOR}"
+    echo ""
+done
+
+
+AVAILABLE_SNAPSHOTS=0
+for height in "${SNAPSHOT_BLOCK_HEIGHT[@]}"; do
+    if [[ "$height" != "N/A" ]]; then
+        ((AVAILABLE_SNAPSHOTS++))
+    fi
+done
+
+if [[ $AVAILABLE_SNAPSHOTS -gt 0 ]]; then
+    read -p "Please choose a snapshot number (1-${#SNAPSHOT_BLOCK_HEIGHT[@]}): " SNAPSHOT_CHOICE
+    if [[ "$SNAPSHOT_CHOICE" =~ ^[1-9][0-9]*$ ]] && [ "$SNAPSHOT_CHOICE" -le "${#SNAPSHOT_BLOCK_HEIGHT[@]}" ]; then
+        SELECTED_BLOCK_HEIGHT=${SNAPSHOT_BLOCK_HEIGHT[$((SNAPSHOT_CHOICE-1))]}
+        echo "You chose snapshot: Snapshot $SNAPSHOT_CHOICE with Block Height: $SELECTED_BLOCK_HEIGHT"
+        
+        read -p "Do you want to continue with synchronization via the selected snapshot? (yes/no): " USER_CHOICE
+        USER_CHOICE=$(echo "$USER_CHOICE" | tr '[:upper:]' '[:lower:]')
+
+        if [[ "$USER_CHOICE" == "yes" || "$USER_CHOICE" == "y" ]]; then
+            echo "Proceeding with synchronization..."
+            snap list | grep -q lz4 || snap install lz4
+            sudo systemctl stop prysmd
+            cp $HOME/.prysm/data/priv_validator_state.json $HOME/.prysm/priv_validator_state.json.backup
+            rm -rf $HOME/.prysm/data
+            SNAPSHOT_NUMBER=$((SNAPSHOT_CHOICE))
+            curl -o - -L "https://server-1.stavr.tech/Testnet/Prysm/prysm-snap-$SNAPSHOT_NUMBER.tar.lz4" | lz4 -c -d - | tar -x -C $HOME/.prysm
+            mv $HOME/.prysm/priv_validator_state.json.backup $HOME/.prysm/data/priv_validator_state.json
+            wget -O $HOME/.prysm/config/addrbook.json "https://server-1.stavr.tech/Testnet/Prysm/addrbook.json"
+            sudo systemctl restart prysmd && journalctl -fu prysmd -o cat
+        else
+            echo "Operation cancelled. Returning to menu..."
+        fi
+    else
+        echo "Invalid selection. Returning to menu..."
+    fi
 else
-    TIME_AGO="$((TIME_DIFF / 86400)) d ago"
-fi
-
-FILE_SIZE=$(echo "$SNAPSHOT_INFO" | grep "Pruned size" | awk '{print $3}')
-
-echo -e "Block Height: ${YELLOW}$BLOCK_HEIGHT${NO_COLOR}"
-echo -e "Creation Time: ${GREEN}$CREATION_TIME_RAW${NO_COLOR}"
-echo -e "File Size (Pruned): ${PINK}$FILE_SIZE${NO_COLOR} (${TIME_AGO})"
-read -p "Do you want to continue with synchronization via Pruned snapshot? (yes/no): " USER_CHOICE
-USER_CHOICE=$(echo "$USER_CHOICE" | tr '[:upper:]' '[:lower:]')
-if [[ "$USER_CHOICE" == "yes" || "$USER_CHOICE" == "y" ]]; then
-    echo "Proceeding with synchronization..."
-    snap list | grep -q lz4 || snap install lz4
-    sudo systemctl stop prysmd
-    cp $HOME/.prysm/data/priv_validator_state.json $HOME/.prysm/priv_validator_state.json.backup
-    rm -rf $HOME/.prysm/data
-    curl -o - -L https://prysm-t.snapshot.stavr.tech/prysm-snap.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.prysm/
-    curl -o - -L https://prysm-t.wasm.stavr.tech/wasm-prysm.tar.lz4 | lz4 -c -d - | tar -x -C $HOME/.prysm/
-    mv $HOME/.prysm/priv_validator_state.json.backup $HOME/.prysm/data/priv_validator_state.json
-    wget -O $HOME/.prysm/config/addrbook.json "https://prysm-t.wasm.stavr.tech/addrbook.json"
-    sudo systemctl restart prysmd && journalctl -fu prysmd -o cat
-else
-    echo "Operation cancelled. Returning to menu..."
+    echo "No available snapshots to select. Returning to menu..."
 fi
 
 
@@ -244,8 +328,8 @@ curl localhost:$(sed -n '/\[rpc\]/,/laddr/ { /laddr/ {s/.*://; s/".*//; p} }' $H
 break
 ;;
 "Check Version")
-prysm_output=$(prysmd version --long | grep -e version -e commit 2>&1)
-echo -e "\e[32m${prysm_output}\e[0m"
+version_output=$(prysmd version --long | grep -e version -e commit 2>&1)
+echo -e "\e[32m${version_output}\e[0m"
 
 break
 ;;
@@ -256,11 +340,10 @@ curl -s http://localhost:$RPC_PORT/status | jq .result.sync_info
 break
 ;;
 "Sync status")
-RPC_PORT=$(sed -n '90{s/.*://; s/"//g; p}' $HOME/.prysm/config/config.toml)
-
+RPC_PORT=$(grep '^laddr' $HOME/.prysm/config/config.toml | head -n 1 | awk -F':' '{print $NF}' | tr -d '"')
 while true; do
     local_height=$(curl -s localhost:$RPC_PORT/status | jq -r '.result.sync_info.latest_block_height')
-    network_height=$(curl -s https://t-prysm.rpc.utsa.tech/status | jq -r '.result.sync_info.latest_block_height')
+    network_height=$(curl -s https://prysm.rpc.t.stavr.tech/status | jq -r '.result.sync_info.latest_block_height')
     blocks_left=$((network_height - local_height))
     
     estimated_time=$(echo "$blocks_left * 1.60" | bc)
@@ -281,14 +364,14 @@ read confirmation
 if [ "$confirmation" == "Yes" ]; then
     echo -e "\e[32m$confirmation\e[0m - Starting deletion process."
 
-    sudo systemctl stop prysmd
-	sudo systemctl disable prysmd
-	rm /etc/systemd/system/prysmd.service
-	sudo systemctl daemon-reload
-	cd $HOME
-	rm -rf prysm
-	rm -rf .prysm
-	rm -rf $(which prysmd)
+sudo systemctl stop prysmd
+sudo systemctl disable prysmd
+rm /etc/systemd/system/prysmd.service
+sudo systemctl daemon-reload
+cd $HOME
+rm -rf prysm
+rm -rf .prysm
+rm -rf $(which prysmd)
 
     echo "Node has been successfully deleted."
 else
